spring:
  datasource:
    # localhost -> mysql (docker-compose의 서비스 이름)로 변경
    url: jdbc:mysql://mysql:3306/pokemon_store?serverTimezone=Asia/Seoul
    username: root
    password: vhzptahs12
  
  data:
    redis:
      # localhost -> redis (docker-compose의 서비스 이름)로 변경
      host: redis
      port: 6379

  # 2. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        use_sql_comments: true
        # [★복구] 아까 잘려나간 핵심 설정입니다!
        

  # 3. AWS S3 설정
  cloud:
    aws:
      s3:
        bucket: pkm-store-image-bucket
      region:
        # [★수정] ap-northeast-2 가 서울입니다! (southeast는 호주 시드니입니다)
        static: ap-northeast-2 
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace 

# JWT 설정
jwt:
  secret: my-super-secret-key-for-pokemon-store-backend-must-be-long
  expiration: 3600000

# application.yaml의 맨 아래에 추가합니다.
toss:
  # 토스페이먼츠 개발자 센터에서 발급받은 '테스트 시크릿 키' (운영 시에는 실결제 키로 교체)
  secret-key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R